# Generated by Django 5.2.7 on 2025-10-24 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=100)),
                ('home_sqft', models.IntegerField()),
                ('home_bedrooms', models.IntegerField()),
                ('home_bathrooms', models.IntegerField()),
                ('home_acquired', models.DateField()),
                ('home_photo', models.ImageField(blank=True, null=True, upload_to='home_photos/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=30)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_name', models.CharField(blank=True, max_length=50)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.profile')),
            ],
        ),
    ]
