# Generated by Django 5.2.7 on 2025-10-27 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0002_home_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(max_length=350)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.home')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.vehicle')),
            ],
        ),
    ]
