# Generated by Django 5.2.7 on 2025-10-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0004_alter_category_options_alter_category_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.home'),
        ),
        migrations.AlterField(
            model_name='category',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.vehicle'),
        ),
    ]
