# Generated by Django 5.2.7 on 2025-10-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0005_alter_category_home_alter_category_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
