# Generated by Django 5.2.7 on 2025-10-28 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0006_alter_category_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True, max_length=350, null=True)),
                ('task_xp_reward', models.IntegerField(default=10)),
                ('task_xp_random', models.IntegerField(blank=True, default=0, null=True)),
                ('task_is_complete', models.BooleanField(default=False)),
                ('task_date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('task_date_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.category')),
            ],
        ),
    ]
