# Generated by Django 5.2.7 on 2025-10-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0007_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, help_text='Upload photos of receipts, completed work, or reference images', null=True, upload_to='task_photos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
