# Generated by Django 5.2.7 on 2025-10-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0008_task_task_image_task_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_is_complete',
            field=models.BooleanField(default=False, help_text='Check the box once you have completed this task'),
        ),
    ]
