# Generated by Django 5.2.7 on 2025-10-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0010_alter_task_task_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['category', '-task_date_created']},
        ),
    ]
