# Generated by Django 5.2.7 on 2025-10-30 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_tracker', '0011_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_gained', models.IntegerField()),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.profile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixit_tracker.task')),
            ],
        ),
    ]
